---
new_page_extension: md
auto_deploy: false
admin_path: "/admin/"
webhook_url: 
collections:
  _history:
    default_front_matter_template: history
  _timeline:
    default_front_matter_template: timeline
  _updates:
    default_front_matter_template: updates
upload_dir: uploads
public_path: "/uploads"
front_matter_path: "/uploads"
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
